import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const initialFoods = [
  {
    name: "Whey Protein Isolado",
    category: "Suplementos",
    source: "Rótulo",
    baseQuantity: 100,
    calories: 366.7,
    protein: 90.0,
    carbohydrate: 2.0,
    lipid: 1.0,
    fiber: 0.0,
    sodium: 200.0,
  },
  {
    name: "Albumina Naturovos",
    category: "Suplementos",
    source: "Rótulo",
    baseQuantity: 100,
    calories: 362.0,
    protein: 84.0,
    carbohydrate: 4.0,
    lipid: 0.0,
    fiber: 0.0,
    sodium: 1000.0,
  },
  {
    name: "Soy Protein (Isolada)",
    category: "Suplementos",
    source: "Rótulo",
    baseQuantity: 100,
    calories: 356.7,
    protein: 86.7,
    carbohydrate: 0.0,
    lipid: 0.7,
    fiber: 0.0,
    sodium: 800.0,
  },
  {
    name: "Peito de Frango (Grelhado)",
    category: "Carnes e Aves",
    source: "TACO",
    baseQuantity: 100,
    calories: 165.0,
    protein: 32.0,
    carbohydrate: 0.0,
    lipid: 2.67,
    fiber: 0.0,
    sodium: 52.0,
  },
  {
    name: "Arroz Branco (Cozido)",
    category: "Cereais e Leguminosas",
    source: "TACO",
    baseQuantity: 100,
    calories: 138.0,
    protein: 2.33,
    carbohydrate: 29.0,
    lipid: 1.67,
    fiber: 0.33,
    sodium: 189.0,
  },
  {
    name: "Feijão Carioca (Cozido)",
    category: "Cereais e Leguminosas",
    source: "TACO",
    baseQuantity: 100,
    calories: 79.0,
    protein: 4.67,
    carbohydrate: 14.67,
    lipid: 1.67,
    fiber: 7.0,
    sodium: 190.0,
  },
  {
    name: "Banana Nanica",
    category: "Frutas",
    source: "TACO",
    baseQuantity: 100,
    calories: 91.0,
    protein: 1.33,
    carbohydrate: 21.67,
    lipid: 0.33,
    fiber: 1.67,
    sodium: 0.0,
  },
  {
    name: "Aveia (Flocos)",
    category: "Cereais",
    source: "TACO",
    baseQuantity: 100,
    calories: 379.0,
    protein: 15.67,
    carbohydrate: 64.67,
    lipid: 8.67,
    fiber: 9.67,
    sodium: 4.67,
  },
  {
    name: "Iogurte Natural Desnatado",
    category: "Laticínios",
    source: "TACO",
    baseQuantity: 100,
    calories: 48.0,
    protein: 4.0,
    carbohydrate: 7.0,
    lipid: 0.33,
    fiber: 0.0,
    sodium: 69.0,
  },
  {
    name: "Leite em Pó Integral",
    category: "Laticínios",
    source: "TACO",
    baseQuantity: 100,
    calories: 496.7,
    protein: 26.0,
    carbohydrate: 38.0,
    lipid: 27.0,
    fiber: 0.0,
    sodium: 370.0,
  },
  {
    name: "Ovo de Galinha (Cozido)",
    category: "Ovos",
    source: "TACO",
    baseQuantity: 100,
    calories: 155.0,
    protein: 13.0,
    carbohydrate: 0.65,
    lipid: 10.0,
    fiber: 0.0,
    sodium: 124.0,
  },
  {
    name: "Tomate Cru",
    category: "Verduras e Legumes",
    source: "TACO",
    baseQuantity: 100,
    calories: 18.0,
    protein: 1.0,
    carbohydrate: 4.0,
    lipid: 0.34,
    fiber: 1.2,
    sodium: 5.0,
  },
  {
    name: "Azeite de Oliva",
    category: "Óleos e Gorduras",
    source: "TACO",
    baseQuantity: 100,
    calories: 884.0,
    protein: 0.0,
    carbohydrate: 0.0,
    lipid: 100.0,
    fiber: 0.0,
    sodium: 0.0,
  },
  {
    name: "Pão Francês",
    category: "Pães",
    source: "TACO",
    baseQuantity: 100,
    calories: 300.0,
    protein: 8.33,
    carbohydrate: 58.67,
    lipid: 3.0,
    fiber: 2.33,
    sodium: 648.0,
  },
  {
    name: "Tilápia (Filé Cozido)",
    category: "Peixes e Frutos do Mar",
    source: "TACO",
    baseQuantity: 100,
    calories: 112.0,
    protein: 23.0,
    carbohydrate: 0.0,
    lipid: 2.0,
    fiber: 0.0,
    sodium: 77.0,
  },
  {
    name: "Salmão (Grelhado)",
    category: "Peixes e Frutos do Mar",
    source: "TACO",
    baseQuantity: 100,
    calories: 216.7,
    protein: 25.33,
    carbohydrate: 0.0,
    lipid: 12.67,
    fiber: 0.0,
    sodium: 72.3,
  },
];

async function main() {
  console.log("Seeding FoodItem database...");

  for (const food of initialFoods) {
    await prisma.foodItem.upsert({
      where: { id: food.name },
      update: food,
      create: {
        id: food.name,
        ...food,
      },
    });
  }

  // Create default patient Paulo Vitor R de Sousa
  const patient = await prisma.patient.upsert({
    where: { id: "paulo-vitor-default" },
    update: {},
    create: {
      id: "paulo-vitor-default",
      name: "Paulo Vitor R de Sousa",
      email: "paulo.vitor@nutriax.com",
      gender: "Masculino",
      age: 38,
      height: 1.96,
      currentWeight: 116.0,
      usualWeight: 120.61,
      targetWeight: 103.72,
      objective: "Perda de peso",
      patientType: "Praticante recreativo",
      mainModality: "Musculação",
      cardioType: "HIIT",
      workoutFrequency: "6x/semana",
      workoutSplit: "ABC",
      workoutVolume: "Alto",
      cardioFrequency: "3x/semana",
      cardioDuration: "Até 15 min",
      cardioIntensity: "Moderada",
      neatRoutine: "Baixo",
      dailySteps: "5.000–7.499",
      workRoutine: "Sentado",
      averageSleep: "7–8 h/noite",
      sleepQuality: "Boa",
      stressLevel: "Moderado",
      cookingAvailability: "Diariamente",
      eatingOutFreq: "1x/semana",
      performanceGoal: "Hipertrofia",
    },
  });

  console.log(`Seeded patient: ${patient.name}`);
  console.log("Seeding completed successfully.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
